apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment-green
  namespace: microapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: products
      version: green
  template:
    metadata:
      labels:
        app: products
        version: green
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5003"
    spec:
      containers:
        - name: products
          image: xsonts/microproductos:PLACEHOLDER_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: CONSUL_HOST
              value: "consul-svc"
            - name: SERVICE_NAME
              value: "products-service"
            - name: SERVICE_PORT
              value: "5003"
            - name: SERVICE_HOST
              value: "microproductos"
            - name: MYSQL_HOST
              value: "db-products-svc"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"
            - name: MYSQL_DB
              value: "productos"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 10
